# GENERATED by build/render.py from build/precompute/chip_precompute.py.
# Do not edit -- run `make -C build` instead.
#
# The solver that BUILDS the chip tables is 796 lines long and
# runs offline. The bot needs 4 names out of it
# (ALL_CELLS, bestmove_lookup, DIAGONALS, wins_barrier), which pull in 18 definitions in total.
# Everything else used to be uploaded with the submission and never called.


ORIGIN = (0, 0)

TARGET_TILES = [(1, 0), (-1, 0), (0, 1), (0, -1)]

_OUTER_SEED = [(0, 2), (1, 2), (1, 1), (2, 1)]

def _rot(p):
    return (-p[1], p[0])

def _rotations(p):
    out = []
    for _ in range(4):
        out.append(p)
        p = _rot(p)
    return out

OUTER_TILES = sorted({r for seed in _OUTER_SEED for r in _rotations(seed)})

ALL_CELLS = sorted({ORIGIN, *TARGET_TILES, *OUTER_TILES})

_D4 = [lambda x, y: (x, y), lambda x, y: (-y, x), lambda x, y: (-x, -y), lambda x, y: (y, -x), lambda x, y: (x, -y), lambda x, y: (-x, y), lambda x, y: (y, x), lambda x, y: (-y, -x)]

def _perm(tiles, g):
    idx = {t: i for i, t in enumerate(tiles)}
    return [idx[g(*t)] for t in tiles]

_DIAG_OFF = [(1, 1), (-1, 1), (1, -1), (-1, -1)]

_CPERM = [_perm(TARGET_TILES, g) for g in _D4]

_DPERM = [_perm(_DIAG_OFF, g) for g in _D4]

def _xform_config(codes, dmask, gi):
    nc = [0, 0, 0, 0]
    for p in range(4):
        nc[_CPERM[gi][p]] = codes[p]
    nd = 0
    for j in range(4):
        if dmask >> j & 1:
            nd |= 1 << _DPERM[gi][j]
    return (tuple(nc), nd)

def canonicalize(codes, dmask):
    """Return (canon_codes, canon_dmask, gi) where gi maps the input to canonical."""
    best, bestg = (None, 0)
    for gi in range(8):
        key = _xform_config(tuple(codes), dmask, gi)
        if best is None or key < best:
            best, bestg = (key, gi)
    return (best[0], best[1], bestg)

def bestmove_lookup(table, codes, dmask, hp, htile):
    """Optimal target to attack. codes: 4 cardinal codes; hp: list in my-target order
    (targets are cardinals with code 2/3, ascending position); htile: healer's cluster
    offset (x,y) from the stand tile. Returns my-target-order index, or None."""
    cc, cd, gi = canonicalize(tuple(codes), dmask)
    entry = table.get((cc, cd))
    if entry is None:
        return None
    maxhalfs, tlist, buf = entry
    tidx = {t: i for i, t in enumerate(tlist)}
    gx, gy = _D4[gi](*htile)
    if (gx, gy) not in tidx:
        return None
    ti = tidx[gx, gy]
    my_T = [p for p in range(4) if codes[p] in (2, 3)]
    canon_T = [q for q in range(4) if cc[q] in (2, 3)]
    canon_hp = [0] * len(canon_T)
    for mi, p in enumerate(my_T):
        canon_hp[canon_T.index(_CPERM[gi][p])] = hp[mi]
    hidx = 0
    for h, m in zip(canon_hp, maxhalfs):
        if h < 1:
            h = 1
        elif h > m:
            h = m
        hidx = hidx * m + (h - 1)
    bm = buf[hidx * len(tlist) + ti]
    if bm == 255:
        return None
    canon_pos = canon_T[bm]
    for mi, p in enumerate(my_T):
        if _CPERM[gi][p] == canon_pos:
            return mi
    return None

def _hp_index(hp_halves, maxhalfs):
    idx = 0
    for h, m in zip(hp_halves, maxhalfs):
        idx = idx * m + (h - 1)
    return idx

DIAGONALS = [(1, 1), (-1, 1), (1, -1), (-1, -1)]

def wins_barrier(filt, cardinal_codes, dmask, halfhp):
    """O(1): does A guarantee a kill for config (cardinal_codes, diagonal_mask=dmask)
    at the given half-HPs (one per conv/harv neighbour, in cardinal order)?"""
    entry = filt.get((tuple(cardinal_codes), dmask))
    if entry is None:
        return False
    maxhalfs, bits = entry
    hp = []
    j = 0
    for code in cardinal_codes:
        if code in (2, 3):
            h = halfhp[j]
            j += 1
            if h < 1:
                return True
            hp.append(min(h, maxhalfs[len(hp)]))
    idx = _hp_index(hp, maxhalfs)
    return bool(bits[idx >> 3] & 1 << (idx & 7))
